defaults:
  - _data_type_: gt

name: dsprites_imagenet_fg_20

data:
  _target_: research.code.dataset.data.DSpritesImagenetData
  visibility: 20
  mode: fg
  data_root: ${dsettings.storage.data_root}
  prepare: ${dsettings.dataset.prepare}
  in_memory: ${dsettings.dataset.try_in_memory}

transform:
  _target_: disent.dataset.transform.ToImgTensorF32
  mean: ${dataset.meta.vis_mean}
  std: ${dataset.meta.vis_std}

meta:
  x_shape: [3, 64, 64]
  vis_mean: [0.038064750024334834, 0.03766780505193579, 0.03719798677641122]
  vis_std: [0.17498878664096565, 0.17315570657628315, 0.1709923319496426]
