defaults:
  - _input_mode_: triplet

name: softadatvae

cfg:
  _target_: research.code.frameworks.vae.SoftAdaTripletVae.cfg
  # base ae
  recon_loss: ${settings.framework.recon_loss}
  loss_reduction: ${settings.framework.loss_reduction}
  # base vae
  latent_distribution: ${settings.framework_opt.latent_distribution}
  # disable various components
  detach_decoder: FALSE
  disable_reg_loss: FALSE
  disable_rec_loss: FALSE
  disable_aug_loss: FALSE
  # Beta-VAE
  beta: ${settings.framework.beta}
  # tvae: triplet stuffs
  triplet_loss: triplet_soft
  triplet_margin_min: NULL
  triplet_margin_max: NULL
  triplet_scale: 1.0
  triplet_p: 1
  # adavae
  ada_thresh_ratio: 0.5
  # ada_tvae - loss
  softada_scale_slope: 0.5

meta:
  model_z_multiplier: 2
