name: basic

augment_cls:
  _target_: torchvision.transforms.RandomOrder
  transforms:
    - _target_: kornia.augmentation.ColorJitter
      p: 0.5
      brightness: 0.25
      contrast: 0.25
      saturation: 0
      hue: 0.15

# THIS IS BUGGY ON BATCH
#    - _target_: kornia.augmentation.RandomSharpness
#      p: 0.5
#      sharpness: 0.5

    - _target_: kornia.augmentation.RandomCrop
      p: 0.5
      size: [64, 64]
      padding: 8

    - _target_: kornia.augmentation.RandomPerspective
      p: 0.5
      distortion_scale: 0.15

    - _target_: kornia.augmentation.RandomRotation
      p: 0.5
      degrees: 9

#    - _target_: kornia.augmentation.RandomResizedCrop
#      p: 0.5
#      size: [64, 64]
#      scale: [0.95, 1.05]
#      ratio: [0.95, 1.05]

# THIS REPLACES MOST OF THE ABOVE BUT IT IS BUGGY ON BATCH
#    - _target_: kornia.augmentation.RandomAffine
#      p: 0.5
#      degrees: 10
#      translate: [0.14, 0.14]
#      scale: [0.95, 1.05]
#      shear: 5
